services:
  - type: web
    name: ineveryunivers-books-api
    runtime: python
    rootDir: Backend
    buildCommand: pip install -r requirements.txt && python -m database.init_database
    startCommand: gunicorn app:app
